config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :friends_infos
  # get 'index/home'
  root 'index#home'  #change to signIn
  get 'index/About'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/friends_info.rb
class FriendsInfo < ApplicationRecord
    belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

         has_many :friends_info
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/friends_infos_controller.rb
class FriendsInfosController < ApplicationController
  before_action :set_friends_info, only: %i[ show edit update destroy ]
  before_action :authenticate_user!, except: [:index, :show]
  before_action :correct_user, only: [:edit, :update, :destroy]
  # GET /friends_infos or /friends_infos.json
  def index
    @friends_infos = FriendsInfo.all
  end

  # GET /friends_infos/1 or /friends_infos/1.json
  def show
  end

  # GET /friends_infos/new
  def new
    # @friends_info = FriendsInfo.new
    @friends_info = current_user.friends_info.build
  end

  # GET /friends_infos/1/edit
  def edit
  end

  # POST /friends_infos or /friends_infos.json
  def create
    # @friends_info = FriendsInfo.new(friends_info_params)
    @friends_info = current_user.friends_info.build(friends_info_params)

    respond_to do |format|
      if @friends_info.save
        format.html { redirect_to friends_info_url(@friends_info), notice: "Friends info was successfully created." }
        format.json { render :show, status: :created, location: @friends_info }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @friends_info.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /friends_infos/1 or /friends_infos/1.json
  def update
    respond_to do |format|
      if @friends_info.update(friends_info_params)
        format.html { redirect_to friends_info_url(@friends_info), notice: "Friends info was successfully updated." }
        format.json { render :show, status: :ok, location: @friends_info }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @friends_info.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /friends_infos/1 or /friends_infos/1.json
  def destroy
    @friends_info.destroy

    respond_to do |format|
      format.html { redirect_to friends_infos_url, notice: "Friends info was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  def correct_user
    @friends_info = current_user.friends_info.find_by(id: params[:id])
    redirect_to friends_info_url(@friends_info), notice: "Not Authorized To Edit This Friend" if @friends_info.nil? 
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_friends_info
      @friends_info = FriendsInfo.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def friends_info_params
      params.require(:friends_info).permit(:First_name, :Last_name, :Contact, :Email, :Instagram, :user_id)
    end
  
  end

app/controllers/index_controller.rb
class IndexController < ApplicationController
  def home
  end

  def About
  end  

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/friends_infos_helper.rb
module FriendsInfosHelper
end

app/helpers/index_helper.rb
module IndexHelper
end

app/views/friends_infos/_form.html.erb
<%= form_with(model: friends_info) do |form| %>
  <% if friends_info.errors.any? %>
    <div id="error_explanation"> <%# style="color: red" %>
      <h2><%= pluralize(friends_info.errors.count, "error") %> prohibited this friends_info from being saved:</h2>

      <ul>
        <% friends_info.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  
  <div class="form-group">
    
    <%= form.text_field :First_name, class:"form-control", placeholder:"First Name"  %>
  </div>

  <div class="form-group">
    
    <%= form.text_field :Last_name, class:"form-control", placeholder:"Last Name"  %>
  </div>

  <div class="form-group">
    
    <%= form.text_field :Contact, class:"form-control", placeholder:"Contact"  %>
  </div>

  <div class="form-group">
    
    <%= form.text_field :Email, class:"form-control", placeholder:"Email"  %>
  </div>

  <div class="form-group">
    
    <%= form.text_field :Instagram, class:"form-control", placeholder:"Instagram" %>
  </div>
  
  <div class="form-group">
    <%= form.number_field :user_id, id: :friends_info_user_id, class:"form-control", value:"current_user.id", type: :hidden %>
  </div>

  <div>
    <%= form.submit class:"btn btn-primary mb-2"  %>
  </div>
<% end %>
 

app/views/friends_infos/_friends_info.html.erb
<table id="<%= dom_id friends_info %>", class="table  table-bordered table-hover"><%# table-stripped %>

  <thead class="thead-dark">
    <tr>
      <th>First Name</th>
      <th>Last Name</th>
      <th>Contact</th>
      <th>Email</th>
      <th>Instagram</th>
      
    </tr>
  </thead>
  
  <tr>
    <td>
      <%= friends_info.First_name %>
    </td>
    <td>
      <%= friends_info.Last_name %>
    </td>
    <td>
      <%= friends_info.Contact %>
    </td>
    <td>
      <%= friends_info.Email %>
    </td>
    <td>
      <%= friends_info.Instagram %>
    </td>
  </tr>
</table>

app/views/friends_infos/edit.html.erb
<h1>Edit</h1>

<%= render "form", friends_info: @friends_info %>

<br>

<div>
  <% link_to "Friend's Info", @friends_info, class:"btn btn-secondary" %> 
  <%= link_to "Back to Friends", friends_infos_path, class:"btn btn-dark" %>
</div>

app/views/friends_infos/index.html.erb
<%# <p style="color: green"><%= notice %>

<%# <h1> Friends</h1> %>
 
<table class="table table-sm table-striped table-bordered table-hover">
  <thead class="thead-dark">
    <tr>
      <th>First Name</th>
      <th>Last Name</th>
      <th>Contact</th>
      <%# <th>Email</th>
      <th>Instagram</th> %>
      <th></th>
      <th></th>
    </tr>
  </thead>
  <tbody>
    <% @friends_infos.each do |friends_info|%>
    <tr>
      <td><%=friends_info.First_name%></td>
      <td><%=friends_info.Last_name%></td>
      <td><%=friends_info.Contact%></td>
      <td><%=link_to "More Info", friends_info, class:"btn btn-primary mb-2"%></td>
      <td><%= button_to "Delete", friends_info, method: :delete, data: { confirm: 'Are you sure?' }, class:"btn btn-danger" %></td>
    
    </tr>
    <% end %>
  </tbody>
</table>  
<%= link_to "Create New Friend", new_friends_info_path, class:"btn btn-dark" %>


<%# <div id="friends_infos" >  %>
  <%# <% @friends_infos.each do |friends_info| %>
    <%# <% render friends_info %> 
    <%# <p> %>
      <%# <%= link_to "Show Info", friends_info, class:"btn btn-secondary" %>
    <%# </p> %>
  <%# <% end %>
<%# </div> %>

<%# <%= link_to "Create New Friend", new_friends_info_path, class:"btn btn-dark" %>

app/views/friends_infos/new.html.erb
<h1>New Friend </h1>
<br/>

<%= render "form", friends_info: @friends_info %>

<br>

<div>
  <%= link_to "Back to Friends ", friends_infos_path,  class:"btn btn-secondary" %>
</div>

app/views/friends_infos/show.html.erb
<%= render @friends_info %>

<div>
  <%= link_to "Edit Friend", edit_friends_info_path(@friends_info), class:"btn btn-secondary" %> 
  <%= link_to "Back to friends ", friends_infos_path, class:"btn btn-dark" %>
  <hr class="my-4">
  <%= button_to "Delete", @friends_info, method: :delete, data: { confirm: 'Are you sure?' }, class:"btn btn-danger" %>
</div>

app/views/index/About.html.erb
<div class="jumbotron">
  <h1 class="display-4">Hii There <%if user_signed_in?%> UserName<%else%>New User<%end%></h1>
  <p class="lead">This is an easy to use Application that enables you to create and keep a record of your friends Contact Information which only you can view.</p>-
  <hr class="my-4">
  <p>In our Friends App you can store details such as:<br/>1.Phone Contacts  2.Email Address  3.Instagram Account  4.Twitter Account  5.And Many More... </p>  
  
    <%if user_signed_in?%>
        <%= link_to "Back to Friends", friends_infos_path, class:"btn btn-dark" %>                                                                                      
    <%else%>
  <%=link_to "SignUp Now", new_user_registration_path, class:"btn btn-primary btn-lg"%>
    <%end%>
</div>

app/views/index/_header.html.erb
<nav class="navbar navbar-expand-lg navbar-light" style="background-color: #e3f2fd;">
  <div class="container-fluid">
    <%if user_signed_in?%>
      <%= link_to "FriendsInfo", friends_infos_path, class:"navbar-brand"%>
    <%else%>
      <%= link_to "Friends Info", new_user_session_path, class:"navbar-brand"%>
    <%end%>
    <%# <a class="navbar-brand" href="#">Rails Practice</a> %>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">

        <% if user_signed_in? %>
          
        <li class="nav-item">
            <%= link_to "Friends", friends_infos_path, class:"nav-link"%>
          <%# <a class="nav-link active" aria-current="page" href="#home.html.erb">About</a> %>
        </li>

        <li class="nav-item">
            <%= link_to "Create", new_friends_info_path, class:"nav-link"%>
          <%# <a class="nav-link active" aria-current="page" href="#home.html.erb">About</a> %>
        </li>

        <li class="nav-item">
          <%= link_to "SignOut", destroy_user_session_path, class:"nav-link"%>
        </li>

        <li class="nav-item">
          <%= link_to "Edit Profile", edit_user_registration_path, class:"nav-link"%>
        </li>
        
        <li class="nav-item">
          <%= link_to "About", index_About_path, class:"nav-link"%>
        </li>

        <% else %>  
        <li class="nav-item">
          <%= link_to "SignIn", new_user_session_path, class:"nav-link"%>
        </li>
             
                
        <li class="nav-item">
          <%= link_to "SignUp", new_user_registration_path, class:"nav-link active"%>
        </li>

        <li class="nav-item">
          <%= link_to "About", index_About_path, class:"nav-link"%>
        </li>

        <% end %>
        <%# <li class="nav-item">
          <a class="nav-link" href="#">Link</a>
        </li> %>

        <%# <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
            Dropdown
          </a>
          <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
            <li><a class="dropdown-item" href="#">Action</a></li>
            <li><a class="dropdown-item" href="#">Another action</a></li>
            <li><hr class="dropdown-divider"></li>
            <li><a class="dropdown-item" href="#">Something else here</a></li>
          </ul>
        </li> %>

        <%# <li class="nav-item">
          <a class="nav-link disabled" href="#" tabindex="-1" aria-disabled="true">Disabled</a>
        </li> %>

      </ul>
      <form class="d-flex">
        <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
        <button class="btn btn-outline-success" type="submit">Search</button>
      </form>
    </div>
  </div>
</nav>

app/views/layouts/_alert.html.erb
<div class="alert alert-warning alert-dismissible fade show" role="alert">
  <%= notice %>
  <button type="button" class="close" data-dismiss="alert" aria-label="Close">
    <span aria-hidden="true">&times;</span>
  </button>
</div>







<%# <div class="alert alert-warning alert-dismissible fade show" role="alert">   %>
  <%# <% flash.each do |key, message| %> 
    <%# <div class="alert <%= key %>
      <%# <%= message %> 
    <%# </div> %>
  <%# <% end %> 
  
  <%# <button type="button" class="close" data-dismiss="alert" aria-label="Close"> %>
    <%# <span aria-hidden="true">&times;</span> %>
  <%# </button> %>

<%# </div> %>


  
<%# <div class=”alert alert-success alert-dismissible”> <a href=”#” class=”close” data-
dismiss=”alert” aria-label=”close”>&times;</a>
</div> %>   

app/views/layouts/application.html.erb
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Rails Practice</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>

    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-KK94CHFLLe+nY2dmCWGMq91rCGa5gtU4mk92HdvYe+M/SXH301p5ILy+dN9+nJOZ" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css" integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2" crossorigin="anonymous">
  </head>
  <body>

    <%= render "index/header"%>  <%# partial %>
    <div class="container">
      <br/>
      <% if notice%>
        <%=render "layouts/alert"%>
      <%end%>
      <br/>
      <%= yield %>
  
    </div>
    <script src="https://cdn.jsdelivr.net/npm/jquery@3.5.1/dist/jquery.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.6.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-Fy6S3B9q64WdZWQUiU+q4/2Lc9npb8tCaSX9FK7E8HnRr0Jz8D6OP9dO5Vg3Q9ct" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ENjdO4Dr2bkBIFxQpeoTz1HIcje39Wm4jDKdf19U8gI4ddQ3GYNS7NTKfAdVQSZe" crossorigin="anonymous"><script>
      $(document).ready(function() {
        $('.alert').each(function() {
          var alertDuration = 5; // Adjust the duration (in milliseconds) as per your requirement
          var $alert = $(this);

          setTimeout(function() {$alert.fadeOut('slow');}, alertDuration);
        });        
      });
    </script>

  </body>
</html>